### ISSUE TITLE
CSparse SparseCholesky vs. PCG

### ISSUE THREAD

**Issue by ajos6183** [wo80/mathnet-extensions#1]
Hi @wo80,

As you may know, i tried your CSparse solver before and i was very happy with its performance. Then i came across this project of yours and i thought that the PCG solver would be faster than the SparseCholesky. However, i noticed that the SparseCholesky of CSparse was a lot faster for sparse matrices that i experimented on. Is there a reason for this?

Regards,
Anthony

**Comment by wo80** [comment]
I'm afraid, there's no easy answer to your question. In general, the performance of an iterative solver largely depends on the preconditioner used, and SSOR is itself very slow. For a symmetric matrix, a better choice would be the incomplete Cholesky factorization.

When using MathNet, my preferred choice is BiCGStab with MILU0 preconditioning.

**Comment by ajos6183** [comment]
Thanks, I guess the implementation in CSparse is too efficient! I'll stick to this one as it seems a lot faster than all MathNet solvers! Appreciate your prompt response!
